services:
  validator:
    build:
      context: ./validator
      dockerfile: Dockerfile
    container_name: fhir-validator
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx4g # Adjust memory allocation as needed
      - FHIR_VERSION=4.0
      - TX_SERVER=https://nginx/fhir
      # - IG_PARAMS=-ig /igs/de.medizininformatikinitiative.kerndatensatz.base-2026.0.0.tgz
      - IG_PARAMS=
          -ig de.basisprofil.r4#1.5.4
          -ig de.medizininformatikinitiative.kerndatensatz.meta#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.base#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.laborbefund#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.medikation#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.consent#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.bildgebung#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.biobank#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.molgen#2026.0.4
          -ig de.medizininformatikinitiative.kerndatensatz.onkologie#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.patho#2026.0.0
          -ig de.medizininformatikinitiative.kerndatensatz.icu#2026.0.0-ballot
    volumes:
      - ./validator/config:/config:ro
      - ./igs:/igs:ro
      - ./nginx/certs/self-signed.crt:/etc/nginx/certs/self-signed.crt:ro
      # Uncomment to persist package cache for offline use:
      - fhir-package-cache:/root/.fhir/packages
    networks:
      - fhir-network
    depends_on:
      nginx:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: fhir-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - fhir-network
    restart: unless-stopped

networks:
  fhir-network:
    driver: bridge

# Uncomment to persist FHIR package cache for offline operation:
volumes:
  fhir-package-cache:
